### ISSUE TITLE
Deleting file from storage if None is assigned

### ISSUE THREAD

**Issue by pyiotr** [rstit/flask-image-alchemy#1]
Assigning `None` to `StdImageFiled` must cause removal file from storage.
Current flow:
```python
user = User.query.first()
user.avatar.delete() # Deleting avatar from storage
user.avatar = None
user.save() 
```
Expected behavior:
```python
user = User.query.first()
user.avatar = None
user.save() # save cause deleting avatar from storage
```

**Comment by pyiotr** [comment]
@reticool @linxaddict @JastrzebskiB wdyt about that behavior? it's correct?

**Comment by linxaddict** [comment]
imho expected behaviour you described is correct

**Comment by pyiotr** [comment]
That Pull Request https://github.com/rstit/flask-image-alchemy/pull/4 provide a solution (events)
